include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_local_identifiers: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

