name: crystal
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

