name: crystal
description: "A modern code editor."
publish_to: 'none'

version: 0.1.3-beta.1


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  logging: ^1.3.0
  file_picker: ^8.1.3
  window_manager: ^0.4.3
  http: ^1.2.2
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/themes/
    - assets/images/logo/
  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/crystal-logo-border.png" 
  windows:
    generate: true
    image_path: "assets/images/logo/crystal-logo-border.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/crystal-logo-border.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/crystal-logo.png
  color_dark: "#262626"
  image_dark: assets/images/logo/crystal-logo.png
