name: crystal
description: "A modern code editor."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  logging: ^1.3.0
  file_picker: ^8.1.3
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/themes/
  fonts:
      - family: IBM Plex Mono
        fonts:
          - asset: assets/fonts/IBMPlexMono-Regular.ttf
          - asset: assets/fonts/IBMPlexMono-Bold.ttf
            weight: 400
      - family: IBM Plex Sans
        fonts:
          - asset: assets/fonts/IBMPlexSans-Regular.ttf
          - asset: assets/fonts/IBMPlexSans-Bold.ttf
            weight: 400
