// Mocks generated by Mockito 5.4.4 from annotations
// in crystal/test/mocks/mock_selection_manager.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:crystal/core/editor/buffer_manager.dart' as _i3;
import 'package:crystal/core/editor/selection_manager.dart' as _i2;
import 'package:crystal/models/selection/selection_direction.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SelectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectionManager extends _i1.Mock implements _i2.SelectionManager {
  MockSelectionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get anchor => (super.noSuchMethod(
        Invocation.getter(#anchor),
        returnValue: 0,
      ) as int);

  @override
  set anchor(int? _anchor) => super.noSuchMethod(
        Invocation.setter(
          #anchor,
          _anchor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get startIndex => (super.noSuchMethod(
        Invocation.getter(#startIndex),
        returnValue: 0,
      ) as int);

  @override
  set startIndex(int? _startIndex) => super.noSuchMethod(
        Invocation.setter(
          #startIndex,
          _startIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get endIndex => (super.noSuchMethod(
        Invocation.getter(#endIndex),
        returnValue: 0,
      ) as int);

  @override
  set endIndex(int? _endIndex) => super.noSuchMethod(
        Invocation.setter(
          #endIndex,
          _endIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get startLine => (super.noSuchMethod(
        Invocation.getter(#startLine),
        returnValue: 0,
      ) as int);

  @override
  set startLine(int? _startLine) => super.noSuchMethod(
        Invocation.setter(
          #startLine,
          _startLine,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get endLine => (super.noSuchMethod(
        Invocation.getter(#endLine),
        returnValue: 0,
      ) as int);

  @override
  set endLine(int? _endLine) => super.noSuchMethod(
        Invocation.setter(
          #endLine,
          _endLine,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startSelection(
    int? line,
    int? index,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startSelection,
          [
            line,
            index,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteSelection(
    _i3.BufferManager? bufferManager,
    int? currentIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteSelection,
          [
            bufferManager,
            currentIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAll(_i3.BufferManager? bufferManager) => super.noSuchMethod(
        Invocation.method(
          #selectAll,
          [bufferManager],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectRange(
    _i3.BufferManager? bufferManager,
    int? startLine,
    int? startIndex,
    int? endLine,
    int? endIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectRange,
          [
            bufferManager,
            startLine,
            startIndex,
            endLine,
            endIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int selectWord(
    _i3.BufferManager? bufferManager,
    int? cursorLine,
    int? cursorIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectWord,
          [
            bufferManager,
            cursorLine,
            cursorIndex,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isWordCharacter(String? char) => (super.noSuchMethod(
        Invocation.method(
          #isWordCharacter,
          [char],
        ),
        returnValue: false,
      ) as bool);

  @override
  void selectLine(
    _i3.BufferManager? bufferManager,
    int? cursorLine,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectLine,
          [
            bufferManager,
            cursorLine,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSelection(
    _i3.BufferManager? bufferManager,
    _i4.SelectionDirection? direction,
    int? currentIndex,
    int? targetIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSelection,
          [
            bufferManager,
            direction,
            currentIndex,
            targetIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetSelection() => super.noSuchMethod(
        Invocation.method(
          #resetSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasSelection,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getSelectedText(_i3.BufferManager? bufferManager) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedText,
          [bufferManager],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedText,
            [bufferManager],
          ),
        ),
      ) as String);
}
