// Mocks generated by Mockito 5.4.4 from annotations
// in crystal/test/mocks/mock_selection_manager.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:crystal/core/editor/buffer_manager.dart' as _i4;
import 'package:crystal/core/editor/selection_manager.dart' as _i3;
import 'package:crystal/models/editor/selection/selection.dart' as _i2;
import 'package:crystal/models/selection/selection_direction.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSelection_0 extends _i1.SmartFake implements _i2.Selection {
  _FakeSelection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SelectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectionManager extends _i1.Mock implements _i3.SelectionManager {
  MockSelectionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Selection get selection => (super.noSuchMethod(
        Invocation.getter(#selection),
        returnValue: _FakeSelection_0(
          this,
          Invocation.getter(#selection),
        ),
      ) as _i2.Selection);

  @override
  set selection(_i2.Selection? _selection) => super.noSuchMethod(
        Invocation.setter(
          #selection,
          _selection,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get startLine => (super.noSuchMethod(
        Invocation.getter(#startLine),
        returnValue: 0,
      ) as int);

  @override
  int get endLine => (super.noSuchMethod(
        Invocation.getter(#endLine),
        returnValue: 0,
      ) as int);

  @override
  int get startIndex => (super.noSuchMethod(
        Invocation.getter(#startIndex),
        returnValue: 0,
      ) as int);

  @override
  int get endIndex => (super.noSuchMethod(
        Invocation.getter(#endIndex),
        returnValue: 0,
      ) as int);

  @override
  int get anchor => (super.noSuchMethod(
        Invocation.getter(#anchor),
        returnValue: 0,
      ) as int);

  @override
  void resetSelection() => super.noSuchMethod(
        Invocation.method(
          #resetSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startSelection(
    int? line,
    int? index,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startSelection,
          [
            line,
            index,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAll(_i4.BufferManager? bufferManager) => super.noSuchMethod(
        Invocation.method(
          #selectAll,
          [bufferManager],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getSelectedText(_i4.BufferManager? bufferManager) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedText,
          [bufferManager],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedText,
            [bufferManager],
          ),
        ),
      ) as String);

  @override
  void deleteSelection(
    _i4.BufferManager? bufferManager,
    int? cursorIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteSelection,
          [
            bufferManager,
            cursorIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasSelection,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void updateSelection(
    _i4.BufferManager? bufferManager,
    _i6.SelectionDirection? direction,
    int? currentIndex,
    int? targetIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSelection,
          [
            bufferManager,
            direction,
            currentIndex,
            targetIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int selectWord(
    _i4.BufferManager? bufferManager,
    int? cursorLine,
    int? cursorIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectWord,
          [
            bufferManager,
            cursorLine,
            cursorIndex,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void selectLine(
    _i4.BufferManager? bufferManager,
    int? cursorLine,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectLine,
          [
            bufferManager,
            cursorLine,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectRange(
    _i4.BufferManager? bufferManager,
    int? startLine,
    int? startIndex,
    int? endLine,
    int? endIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectRange,
          [
            bufferManager,
            startLine,
            startIndex,
            endLine,
            endIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
