// Mocks generated by Mockito 5.4.4 from annotations
// in crystal/test/mocks/mock_selection_manager.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i7;

import 'package:crystal/core/editor/buffer_manager.dart' as _i4;
import 'package:crystal/core/editor/selection_manager.dart' as _i3;
import 'package:crystal/models/editor/selection/selection.dart' as _i2;
import 'package:crystal/models/selection/selection_direction.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSelection_0 extends _i1.SmartFake implements _i2.Selection {
  _FakeSelection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SelectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectionManager extends _i1.Mock implements _i3.SelectionManager {
  @override
  List<_i2.Selection> get selections => (super.noSuchMethod(
        Invocation.getter(#selections),
        returnValue: <_i2.Selection>[],
        returnValueForMissingStub: <_i2.Selection>[],
      ) as List<_i2.Selection>);

  @override
  set selections(List<_i2.Selection>? _selections) => super.noSuchMethod(
        Invocation.setter(
          #selections,
          _selections,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set anchorSelection(_i2.Selection? _anchorSelection) => super.noSuchMethod(
        Invocation.setter(
          #anchorSelection,
          _anchorSelection,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get startLine => (super.noSuchMethod(
        Invocation.getter(#startLine),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get endLine => (super.noSuchMethod(
        Invocation.getter(#endLine),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get startIndex => (super.noSuchMethod(
        Invocation.getter(#startIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get endIndex => (super.noSuchMethod(
        Invocation.getter(#endIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get anchor => (super.noSuchMethod(
        Invocation.getter(#anchor),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clearSelections() => super.noSuchMethod(
        Invocation.method(
          #clearSelections,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startSelection(
    int? line,
    int? index,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startSelection,
          [
            line,
            index,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAll(_i4.BufferManager? bufferManager) => super.noSuchMethod(
        Invocation.method(
          #selectAll,
          [bufferManager],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getSelectedText(_i4.BufferManager? bufferManager) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedText,
          [bufferManager],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedText,
            [bufferManager],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedText,
            [bufferManager],
          ),
        ),
      ) as String);

  @override
  void addSelection(_i2.Selection? selection) => super.noSuchMethod(
        Invocation.method(
          #addSelection,
          [selection],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteSelection(
    _i4.BufferManager? bufferManager,
    int? index,
    int? cursorIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteSelection,
          [
            bufferManager,
            index,
            cursorIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasSelection,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hasMultipleSelections() => (super.noSuchMethod(
        Invocation.method(
          #hasMultipleSelections,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateSelection(
    _i4.BufferManager? bufferManager,
    int? index,
    _i6.SelectionDirection? direction,
    int? currentIndex,
    int? targetIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSelection,
          [
            bufferManager,
            index,
            direction,
            currentIndex,
            targetIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int selectWord(
    _i4.BufferManager? bufferManager,
    int? cursorLine,
    int? cursorIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectWord,
          [
            bufferManager,
            cursorLine,
            cursorIndex,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void selectLine(
    _i4.BufferManager? bufferManager,
    int? index,
    int? cursorLine,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectLine,
          [
            bufferManager,
            index,
            cursorLine,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectRange(
    _i4.BufferManager? bufferManager,
    int? anchor,
    int? index,
    int? startLine,
    int? startIndex,
    int? endLine,
    int? endIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectRange,
          [
            bufferManager,
            anchor,
            index,
            startLine,
            startIndex,
            endLine,
            endIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  (bool, _i2.Selection) isWithinSelection(
    _i4.BufferManager? bufferManager,
    int? line,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWithinSelection,
          [
            bufferManager,
            line,
            index,
          ],
        ),
        returnValue: (
          false,
          _FakeSelection_0(
            this,
            Invocation.method(
              #isWithinSelection,
              [
                bufferManager,
                line,
                index,
              ],
            ),
          )
        ),
        returnValueForMissingStub: (
          false,
          _FakeSelection_0(
            this,
            Invocation.method(
              #isWithinSelection,
              [
                bufferManager,
                line,
                index,
              ],
            ),
          )
        ),
      ) as (bool, _i2.Selection));

  @override
  void removeSelection(_i2.Selection? selection) => super.noSuchMethod(
        Invocation.method(
          #removeSelection,
          [selection],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeOverlappingSelections(_i4.BufferManager? bufferManager) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeOverlappingSelections,
          [bufferManager],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Selection getSelectionAt(
    int? anchor,
    int? startLine,
    int? startIndex,
    int? endLine,
    int? endIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectionAt,
          [
            anchor,
            startLine,
            startIndex,
            endLine,
            endIndex,
          ],
        ),
        returnValue: _FakeSelection_0(
          this,
          Invocation.method(
            #getSelectionAt,
            [
              anchor,
              startLine,
              startIndex,
              endLine,
              endIndex,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeSelection_0(
          this,
          Invocation.method(
            #getSelectionAt,
            [
              anchor,
              startLine,
              startIndex,
              endLine,
              endIndex,
            ],
          ),
        ),
      ) as _i2.Selection);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
