// Mocks generated by Mockito 5.4.4 from annotations
// in crystal/test/mocks/mock_cursor_manager.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:crystal/core/editor/cursor_manager.dart' as _i3;
import 'package:crystal/models/editor/cursor/cursor.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCursor_0 extends _i1.SmartFake implements _i2.Cursor {
  _FakeCursor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CursorManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCursorManager extends _i1.Mock implements _i3.CursorManager {
  @override
  Set<_i2.Cursor> get uniqueCursors => (super.noSuchMethod(
        Invocation.getter(#uniqueCursors),
        returnValue: <_i2.Cursor>{},
        returnValueForMissingStub: <_i2.Cursor>{},
      ) as Set<_i2.Cursor>);

  @override
  List<_i2.Cursor> get cursors => (super.noSuchMethod(
        Invocation.getter(#cursors),
        returnValue: <_i2.Cursor>[],
        returnValueForMissingStub: <_i2.Cursor>[],
      ) as List<_i2.Cursor>);

  @override
  set cursors(List<_i2.Cursor>? _cursors) => super.noSuchMethod(
        Invocation.setter(
          #cursors,
          _cursors,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get targetCursorIndex => (super.noSuchMethod(
        Invocation.getter(#targetCursorIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set targetCursorIndex(int? _targetCursorIndex) => super.noSuchMethod(
        Invocation.setter(
          #targetCursorIndex,
          _targetCursorIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Cursor get anchorCursor => (super.noSuchMethod(
        Invocation.getter(#anchorCursor),
        returnValue: _FakeCursor_0(
          this,
          Invocation.getter(#anchorCursor),
        ),
        returnValueForMissingStub: _FakeCursor_0(
          this,
          Invocation.getter(#anchorCursor),
        ),
      ) as _i2.Cursor);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Cursor firstCursor() => (super.noSuchMethod(
        Invocation.method(
          #firstCursor,
          [],
        ),
        returnValue: _FakeCursor_0(
          this,
          Invocation.method(
            #firstCursor,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCursor_0(
          this,
          Invocation.method(
            #firstCursor,
            [],
          ),
        ),
      ) as _i2.Cursor);

  @override
  _i2.Cursor getCursor(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getCursor,
          [index],
        ),
        returnValue: _FakeCursor_0(
          this,
          Invocation.method(
            #getCursor,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeCursor_0(
          this,
          Invocation.method(
            #getCursor,
            [index],
          ),
        ),
      ) as _i2.Cursor);

  @override
  void setAnchorCursor(_i2.Cursor? cursor) => super.noSuchMethod(
        Invocation.method(
          #setAnchorCursor,
          [cursor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCursors() => super.noSuchMethod(
        Invocation.method(
          #clearCursors,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCursor(_i2.Cursor? cursor) => super.noSuchMethod(
        Invocation.method(
          #addCursor,
          [cursor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCursor(
    _i2.Cursor? cursor, {
    bool? keepAnchor = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeCursor,
          [cursor],
          {#keepAnchor: keepAnchor},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCursorAt(int? index) => super.noSuchMethod(
        Invocation.method(
          #removeCursorAt,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveTo(
    int? index,
    int? line,
    int? column,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveTo,
          [
            index,
            line,
            column,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sortCursors({bool? reverse = false}) => super.noSuchMethod(
        Invocation.method(
          #sortCursors,
          [],
          {#reverse: reverse},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeCursorsIfNeeded() => super.noSuchMethod(
        Invocation.method(
          #mergeCursorsIfNeeded,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveLeft() => super.noSuchMethod(
        Invocation.method(
          #moveLeft,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveRight() => super.noSuchMethod(
        Invocation.method(
          #moveRight,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveUp() => super.noSuchMethod(
        Invocation.method(
          #moveUp,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveDown() => super.noSuchMethod(
        Invocation.method(
          #moveDown,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveToLineStart() => super.noSuchMethod(
        Invocation.method(
          #moveToLineStart,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveToLineEnd() => super.noSuchMethod(
        Invocation.method(
          #moveToLineEnd,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Cursor].
///
/// See the documentation for Mockito's code generation for more information.
class MockCursor extends _i1.Mock implements _i2.Cursor {
  @override
  int get line => (super.noSuchMethod(
        Invocation.getter(#line),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set line(int? _line) => super.noSuchMethod(
        Invocation.setter(
          #line,
          _line,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get index => (super.noSuchMethod(
        Invocation.getter(#index),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set index(int? _index) => super.noSuchMethod(
        Invocation.setter(
          #index,
          _index,
        ),
        returnValueForMissingStub: null,
      );
}
