name: Flutter Desktop Build

permissions:
  contents: write
  id-token: write 

env:
  FLUTTER_VERSION: '3.24.4'
  FLUTTER_CHANNEL: 'stable'
  APP_NAME: 'crystal'

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Windows build
        run: flutter config --enable-windows-desktop
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Create Windows Release Package
        run: |
          $VERSION = "${{ github.ref_name }}"
          if ($VERSION -notmatch '^v') { $VERSION = "v${{ github.run_number }}" }
          $PACKAGE_NAME = "${{ env.APP_NAME }}-windows-$VERSION"
          
          mkdir windows-package
          xcopy /E /I "build\windows\x64\runner\Release\*" "windows-package"
          Compress-Archive -Path windows-package\* -DestinationPath "$PACKAGE_NAME.zip"
      
      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: '*.zip'
          retention-days: 5

  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      
      - name: Build macOS
        run: flutter build macos --release
      
      - name: Create macOS Archive
        run: |
          VERSION="${{ github.ref_name }}"
          if [[ ! $VERSION == v* ]]; then
            VERSION="v${{ github.run_number }}"
          fi
          PACKAGE_NAME="${{ env.APP_NAME }}-macos-$VERSION"
          
          cd build/macos/Build/Products/Release
          ditto -c -k --keepParent *.app "$PACKAGE_NAME.zip"
          mv "$PACKAGE_NAME.zip" $GITHUB_WORKSPACE/
          
      - name: Upload macOS Build
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: '*.zip'
          retention-days: 5

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev fuse libfuse2 \
            libjsoncpp25 libsecret-1-0 libasound2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Linux build
        run: flutter config --enable-linux-desktop
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Setup AppDir
        run: |
          VERSION="${{ github.ref_name }}"
          if [[ ! $VERSION == v* ]]; then
            VERSION="v${{ github.run_number }}"
          fi
          PACKAGE_NAME="${{ env.APP_NAME }}-linux-$VERSION"
          
          mkdir -p AppDir/{usr/{bin,lib,share/{applications,icons/hicolor/256x256/apps}},opt/${{ env.APP_NAME }}}
          cp -r build/linux/x64/release/bundle/* AppDir/opt/${{ env.APP_NAME }}/
          cp assets/images/logo/crystal-logo.png AppDir/usr/share/icons/hicolor/256x256/apps/${{ env.APP_NAME }}.png
          
          # Create wrapper script
          cat > AppDir/usr/bin/${{ env.APP_NAME }} << 'EOL'
          #!/bin/bash
          exec /opt/${{ env.APP_NAME }}/${{ env.APP_NAME }} "$@"
          EOL
          chmod +x AppDir/usr/bin/${{ env.APP_NAME }}
      
      - name: Create desktop file
        run: |
          cat > AppDir/usr/share/applications/${{ env.APP_NAME }}.desktop << EOL
          [Desktop Entry]
          Name=Crystal
          Exec=${{ env.APP_NAME }}
          Icon=${{ env.APP_NAME }}
          Type=Application
          Categories=Development;
          EOL
      
      - name: Build AppImage
        run: |
          VERSION="${{ github.ref_name }}"
          if [[ ! $VERSION == v* ]]; then
            VERSION="v${{ github.run_number }}"
          fi
          PACKAGE_NAME="${{ env.APP_NAME }}-linux-$VERSION"
          
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          
          # Create AppRun
          cat > AppDir/AppRun << 'EOL'
          #!/bin/bash
          HERE="$(dirname "$(readlink -f "${0}")")"
          export PATH="${HERE}/usr/bin:${PATH}"
          export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
          exec "${HERE}/usr/bin/${{ env.APP_NAME }}" "$@"
          EOL
          chmod +x AppDir/AppRun
          
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir "$PACKAGE_NAME.AppImage"
      
      - name: Upload Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: '*.AppImage'
          retention-days: 5

  test-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test || echo "No tests found"

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      
      - name: Prepare Release Files
        run: |
          VERSION="${{ github.ref_name }}"
          if [[ ! $VERSION == v* ]]; then
            VERSION="v${{ github.run_number }}"
          fi
          
          mkdir -p release
          find . -name "*.zip" -o -name "*.AppImage" | while read file; do
            mv "$file" release/
          done
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name == 'main' && format('v{0}', github.run_number) || github.ref_name }}
          name: Release ${{ github.ref_name == 'main' && github.run_number || github.ref_name }}
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
